### PR TITLE
Update Float.TinCan for .NET 6/7

### PR DESCRIPTION
**Pull request by seamasmcgettrick**
SL-6377

### CODE REVIEW

**Comment by seamasmcgettrick** [comment]
@mediabounds I used the Float.FileDownloader updates as a template for the changes here but I think we need to add gitversion actions into the deploy workflow. The build script will so probably need to be updated on fileDownloader and this module.

**Review by mediabounds — DISMISSED** [review]
@seamasmcgettrick Since we're not using the `build.sh` script anymore in the GitHub workflow...should we remove cake and update the readme for building?

**Comment by seamasmcgettrick** [comment]
@mediabounds I changed the way I did things here a bit to align it with the fixes Brian added to FileDownloader. Versioning should now work and tests work with the original action.

**Review by mediabounds — DISMISSED** [review]

**Comment by seamasmcgettrick** [comment]
@mediabounds I am blocked from merging this until it is approved again. The deploy script now only uses build.sh for gitVersion of the assembly files as discussed in slack. Since build script also works I left it intact for local development but it can be removed in the future once gitVersion works directly in deploy script.

**Review by mediabounds — APPROVED** [review]

**Pull request merged**
